#!/bin/bash
prog="bootstrap"

set -e
export PATH=/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin
export TMPDIR=/var/tmp

n_payload_dir=${NEPHO_NephoPayloadDir-"/var/lib/nepho"}
n_log_dir=${NEPHO_NephoLogDir-"/var/log/nepho"}
update_pkgs=${NEPHO_UpdatePackages-"True"}

mkdir -p ${n_log_dir}
log="${n_log_dir}/${prog}.log"

# Pretty print informational and error messages
function message() {
  case $1 in
    fail ) echo -e "\n\033[0m${prog}: \033[1;31m${2}\033[0m" ;;
    info ) echo -e "\n\033[0m${prog}: \033[1;34m${2}\033[0m" ;;
  esac

  echo "  [${1}] ${2}" >> ${n_log_dir}/${prog}.log
}

function update_packages() {
  if [[ $update_pkgs == "True" ]]; then
    # Update all local packages
    message info "Updating packages (this may take a while)"
    yum -y -q update >>"$log" 2>&1
  fi
}

function setup_puppet() {
  message info "Installing Puppet"
  yum install -y puppet facter hiera >>"$log" 2>&1

  if [[ ! -f /etc/puppet/hiera.yaml && -f /etc/hiera.yaml ]]; then
    message info "Symlinking hiera config into /etc/puppet"
    ln -s /etc/hiera.yaml /etc/puppet/hiera.yaml
  fi

  # Symlink hieradata into facter
  if [[ ! -f /etc/facter/facts.d/hiera-defaults.yaml ]]; then
    message info "Setting up facter with hiera data"
    mkdir -p /etc/facter/facts.d
    touch /var/lib/hiera/defaults.yaml
    ln -s /var/lib/hiera/defaults.yaml /etc/facter/facts.d/hiera-defaults.yaml
  fi

  # Fix an error in F19 packaged version of Hiera's default config file
  sed -i 's/- %{\(.*\)}/- "%{\1}"/' /etc/hiera.yaml
}

function install_prereqs() {
  message info "Installing prerequisites"
  puppet resource package git              ensure=installed >>"$log" 2>&1
  puppet resource package python-pip       ensure=installed >>"$log" 2>&1
  puppet resource package awscli           ensure=installed provider=pip >>"$log" 2>&1
  puppet resource package librarian-puppet ensure=installed provider=gem >>"$log" 2>&1

  # Nice-to-haves
  puppet resource package vim-enhanced ensure=installed >>"$log" 2>&1
  puppet resource package tmux         ensure=installed >>"$log" 2>&1
  puppet resource package elinks       ensure=installed >>"$log" 2>&1
}

function populate_hiera() {
  # Populate data from NEPHO_ environment variables
  if [[ ! -s '/var/lib/hiera/defaults.yaml' ]]; then
    message info "Populating hiera data from environment variables"
    ruby -e "require 'yaml'" -e \
      "print Hash[ENV.select { |k,v| k =~ /^NEPHO_/ }.map { |i| [ i.first, i.last] } ].to_yaml" \
      > /var/lib/hiera/defaults.yaml
  else
    message info "Hiera data already present, skipping"
  fi
}

# Make sure we are in the directory of this script
cd $(dirname "${0}")

message info "Beginning run at $(date '+%F %T')"

# Make sure that this script has not already run successfully
if [[ -f /.nepho-bootstrap ]]; then
  message fail "Bootstrap has already run on this instance."
else
  update_packages
  setup_puppet
  install_prereqs
  date > /.nepho-bootstrap
fi

populate_hiera

message info "Run complete at $(date '+%F %T')"

# vim: set ft=sh ts=2 sw=2 ei:
