#!/bin/bash
prog="bootstrap"

set -e
PATH=/bin:/usr/bin:/sbin:/usr/sbin

n_payload_dir=${NEPHO_NephoPayloadDir-"/var/lib/nepho"}
n_log_dir=${NEPHO_NephoLogDir-"/var/log/nepho"}
update_pkgs=${NEPHO_UpdatePackages-"False"}
now="$(date '+%F %T')"

mkdir -p ${n_log_dir}
echo "Beginning run at ${now}" >> ${n_log_dir}/${prog}.log

# Pretty print informational and error messages
function message() {
  case $1 in
    fail ) echo -e "\n\033[0m${prog}: \033[1;31m${2}\033[0m" ;;
    info ) echo -e "\n\033[0m${prog}: \033[1;34m${2}\033[0m" ;;
  esac

  echo "${2}" >> ${n_log_dir}/${prog}.log
}

function setup_puppet() {
  message info "Installing Puppet"
  yum install -y puppet facter hiera
}

function install_packages() {
  if [[ $update_pkgs == "True" ]]; then
    # Update all local packages
    message info "Updating packages (this may take a while)"
    yum -y -q update
  fi

  message info "Installing packages"
  puppet resource package git ensure=installed >/dev/null
  puppet resource package librarian-puppet ensure=installed provider=gem >/dev/null
}

function populate_hiera() {
  if [[ ! -f /etc/puppet/hiera.yaml && -f /etc/hiera.yaml ]]; then
    message info "Symlinking hiera config into /etc/puppet"
    ln -s /etc/hiera.yaml /etc/puppet/hiera.yaml
  fi

  # Populate data from NEPHO_ environment variables
  if [[ ! -s '/var/lib/hiera/defaults.yaml' ]]; then
    message info "Populating hiera data from environment variables"
    ruby -e "require 'yaml'" -e \
      "print Hash[ENV.select { |k,v| k =~ /^NEPHO_/ }.map { |i| [ i.first, i.last] } ].to_yaml" \
      > /var/lib/hiera/defaults.yaml

    # Symlink hieradata into facter
    message info "Setting up facter with hiera data"
    mkdir -p /etc/facter/facts.d
    ln -s /var/lib/hiera/defaults.yaml /etc/facter/facts.d/hiera-defaults.yaml
  else
    message info "Hiera data already present, skipping"
  fi
}

# Make sure we are in the directory of this script
cd $(dirname "${0}")

# Make sure that this script has not already run successfully
if [[ -f /.nepho-bootstrap ]]; then
  message fail "Bootstrap has already run on this instance."
  exit 0
fi

setup_puppet
install_packages
populate_hiera

date > /.nepho-bootstrap

# vim: set ft=sh ts=2 sw=2 ei:
