#!/bin/bash
prog="bootstrap"

set -e
export PATH=/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin
export TMPDIR=/var/tmp

n_payload_dir=${NEPHO_NephoPayloadDir-"/var/lib/nepho"}
n_log_dir=${NEPHO_NephoLogDir-"/var/log/nepho"}
setup_puppet=${NEPHO_SetupPuppet-"True"}
update_pkgs=${NEPHO_UpdatePackages-"False"}

mkdir -p ${n_log_dir}
log="${n_log_dir}/${prog}.log"

# Pretty print informational and error messages
function message() {
  case $1 in
    fail ) echo -e "\n\033[0m${prog}: \033[1;31m${2}\033[0m" ;;
    info ) echo -e "\n\033[0m${prog}: \033[1;34m${2}\033[0m" ;;
  esac

  echo "  [${1}] ${2}" >> "${log}"
}

function update_packages() {
  if [[ $update_pkgs == "True" ]]; then
    # Update all local packages
    message info "Updating packages (this may take a while)"
    yum -y -q update >>"$log" 2>&1
  fi
}

function setup_puppet() {
  message info "Installing Puppet"
  yum install -y puppet facter hiera >>"$log" 2>&1
}

function install_prereqs() {
  message info "Installing prerequisites"
  puppet resource package git              ensure=installed >>"$log" 2>&1
  puppet resource package rubygems         ensure=installed >>"$log" 2>&1
  puppet resource package librarian-puppet ensure=installed provider=gem >>"$log" 2>&1

  if [[ "$(facter ec2_instance_id)" ]]; then
    message info "Install AWS CLI tools"
    puppet resource package python-pip       ensure=installed >>"$log" 2>&1
    puppet resource package awscli           ensure=installed provider=pip >>"$log" 2>&1
  fi
}

function setup_hiera() {
  if [[ -f "${n_payload_dir}/hiera.yaml" ]]; then
    message info "Symlinking cloudlet hiera config into default locations"
    rm -f /etc/hiera.yaml /etc/puppet/hiera.yaml
    ln -s "${n_payload_dir}/hiera.yaml" /etc/hiera.yaml
    ln -s "${n_payload_dir}/hiera.yaml" /etc/puppet/hiera.yaml
  fi
}

function setup_facter() {
  # Enable ec2_* facts in VPC environments
  # See: http://projects.puppetlabs.com/issues/7559
  message info "Enabling EC2 facts for VPCs"
  mkdir -p $(ruby -e 'puts $LOAD_PATH.first')/facter
  curl https://gist.githubusercontent.com/agperson/8696051/raw/10bf5c3e5e6452c82dc6edc03ebad22be283f906/ec2_vpc.rb > $(ruby -e 'puts $LOAD_PATH.first')/facter/ec2_vpc.rb
}

function populate_facter() {
  # Populate data from NEPHO_ environment variables
  message info "Populating facter data from environment variables"
  mkdir -p /etc/facter/facts.d
  ruby -e "require 'yaml'" -e "print Hash[ENV.select { |k,v| k =~ /^NEPHO_/ }.map { |i| [ i.first, i.last] } ].to_yaml" > /etc/facter/facts.d/nepho.yaml
}

# Make sure we are in the directory of this script
cd $(dirname "${0}")

message info "Beginning run at $(date '+%F %T')"

# Make sure that this script has not already run successfully
if [[ -f /.nepho-bootstrap ]]; then
  message fail "Bootstrap has already run on this instance."
else
  [[ "${update_pkgs}" != "False" ]] && update_packages
  [[ "${setup_puppet}" != "False" ]] && setup_puppet
  setup_hiera
  setup_facter
  install_prereqs
  date > /.nepho-bootstrap
fi

populate_facter

message info "Run complete at $(date '+%F %T')"

# vim: set ft=sh ts=2 sw=2 ei:
