#!/bin/bash
prog="deploy"

n_payload_dir=${NEPHO_NephoPayloadDir-"/var/lib/nepho"}
n_log_dir=${NEPHO_NephoLogDir-"/var/log/nepho"}
n_role=${NEPHO_Role}

# Pretty print informational and error messages
function message() {
  case $1 in
    fail ) echo -e "\n\033[0m${prog}: \033[1;31m${2}\033[0m" ;;
    info ) echo -e "\n\033[0m${prog}: \033[1;34m${2}\033[0m" ;;
  esac

  echo "${2}" >> ${n_log_dir}/${prog}.log
}

message info "Beginning run at $(date '+%F %T')"

# Make sure we are in the directory of this script
cd $(dirname "${0}")

message info "Running cfn-hup daemon"
cfn-hup

if [[ "$n_role" == "all-in-one" ]]; then
  # Ensure all services are running
  # openshift-gears
  # openshift-iptables-port-proxy
  # openshift-node-web-proxy
  # openshift-tc stop/start
  for service in activemq httpd mcollective mongod oddjobd openshift-broker openshift-console; do
    systemctl status $service >/dev/null 2>&1
    if [[ $? -ne 0 ]]; then
      message info "Starting service $service"
      systemctl start $service
    fi
  done
fi

message info "Run complete at $(date '+%F %T')"

exit 0
