#!/bin/bash
prog="deploy"

n_payload_dir=${NEPHO_NephoPayloadDir-"/var/lib/nepho"}
n_log_dir=${NEPHO_NephoLogDir-"/var/log/nepho"}
n_role=${NEPHO_Role}
now="$(date '+%F %T')"

echo "Beginning run at ${now}" >> ${n_log_dir}/${prog}.log

# Pretty print informational and error messages
function message() {
  case $1 in
    fail ) echo -e "\n\033[0m${prog}: \033[1;31m${2}\033[0m" ;;
    info ) echo -e "\n\033[0m${prog}: \033[1;34m${2}\033[0m" ;;
  esac

  echo "${2}" >> ${n_log_dir}/${prog}.log
}

# Make sure we are in the directory of this script
cd $(dirname "${0}")

if [[ "$n_role" == "all-in-one" ]]; then
  # Ensure all services are running
  for service in httpd mcollective mongod openshift-broker openshift-console; do
    systemctl status $service >/dev/null 2>&1
    if [[ $? -ne 0 ]]; then
      echo "Starting service $service"
      systemctl start $service
    fi
  done
else
  message fail "No deployment actions"
fi

exit 0
